apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-terraform-infra
  title: Azure Infra Terraform Template
  description: Scaffold Terraform configuration to provision Azure infra
spec:
  owner: sre-team
  type: infrastructure

  parameters:
    - title: Azure Resource Group
      required:
        - resource_group_name
        - resource_group_tag
      properties:
        resource_group_name:
          type: string
          description: Name of the Resource Group
        resource_group_tag:
          type: string
          description: Tag (e.g., department: SRE)

    - title: Azure Storage Account
      required:
        - storage_account_name
        - storage_account_resource_group
        - sku
        - access_tier
        - storage_account_tag
      properties:
        storage_account_name:
          type: string
        storage_account_resource_group:
          type: string
          default: sre-challenge-flaschenpost
        sku:
          type: string
          enum: [Standard_LRS, Premium_LRS, Standard_GRS]
          default: Standard_LRS
        access_tier:
          type: string
          enum: [Hot, Cool]
          default: Hot
        storage_account_tag:
          type: string
          default: department: SRE

    - title: Azure Container
      required:
        - container_name
        - container_type
      properties:
        container_name:
          type: string
          default: sre
        container_type:
          type: string
          enum: [private, blob]
          default: private

  steps:
    - id: fetch-base
      name: Fetch Terraform Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          resource_group_name: ${{ parameters.resource_group_name }}
          resource_group_tag: ${{ parameters.resource_group_tag }}
          storage_account_name: ${{ parameters.storage_account_name }}
          storage_account_resource_group: ${{ parameters.storage_account_resource_group }}
          sku: ${{ parameters.sku }}
          access_tier: ${{ parameters.access_tier }}
          storage_account_tag: ${{ parameters.storage_account_tag }}
          container_name: ${{ parameters.container_name }}
          container_type: ${{ parameters.container_type }}

  output:
    links:
      - title: Open Result in Repository
        url: ${{ steps.fetch-base.output.repoUrl }}